// Readability + safe-zone audit.
// For every text element: how long it is fully readable on screen, its word
// count, reading pace, and whether its box stays inside the social-UI safe area.
//   node tools/audit.mjs > docs/readability_audit.md
import { chromium } from 'playwright';
import path from 'node:path';

const SAFE = { top: 240, bottom: 1480, left: 60, right: 1020 };
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1080, height: 1920 } });
await page.goto('file://' + path.resolve('video/index.html'));
await page.waitForFunction(() => window.__ready === true);

const rows = await page.evaluate((SAFE) => {
  const sel = [
    '.hook-title span', '.cap', '.cover .brand', '.cover .sub', '.cover .tagline', '.cover .proof',
    '#s-invite .big', '#s-invite .q', '#s-invite .toc li',
    '.kicker', '.headline', '.name', '.price .amt', '.type', '.badge .pill', '.stat',
    '.pixie .pname', '.pixie .ptype', '.pixie .pline', '.pixie .hdr', '.pixie .five', '.pixie .choose', '.opt', '.pixie .or', '.pixie .fine div',
    '.extras .kick2', '.extras .h', '.extras .line1', '.extras .line2',
    '.how .h', '.how .step', '.how .cta',
    '.closing .line', '.closing .sub', '.closing .web', '.closing .ig', '.closing .ph',
  ];
  const els = [...new Set(sel.flatMap((s) => [...document.querySelectorAll(s)]))];
  const readable = (el) => {
    const scene = el.closest('.scene');
    if (!scene || getComputedStyle(scene).visibility === 'hidden') return false;
    let n = el, op = 1;
    while (n && n !== document.body) { const cs = getComputedStyle(n); if (cs.visibility === 'hidden' || cs.display === 'none') return false; op *= +cs.opacity; n = n.parentElement; }
    return op > 0.85;
  };
  // union of the rendered glyph boxes of every text node (not the container box)
  const textBox = (el) => {
    const w = document.createTreeWalker(el, NodeFilter.SHOW_TEXT);
    let x1 = 1e9, y1 = 1e9, x2 = -1e9, y2 = -1e9, n;
    while ((n = w.nextNode())) {
      if (!n.textContent.trim()) continue;
      const r = document.createRange(); r.selectNodeContents(n);
      for (const b of r.getClientRects()) { x1 = Math.min(x1, b.left); y1 = Math.min(y1, b.top); x2 = Math.max(x2, b.right); y2 = Math.max(y2, b.bottom); }
    }
    return [x1, y1, x2, y2].map(Math.round);
  };
  const step = 0.1, stats = els.map(() => ({ best: 0, cur: 0, start: null, bestStart: null, box: null, boxes: [], bestBoxes: [] }));
  for (let t = 0; t <= window.DURATION; t += step) {
    window.renderAt(t);
    els.forEach((el, i) => {
      const s = stats[i];
      if (readable(el)) {
        if (s.cur === 0) { s.start = t; s.boxes = []; }
        s.cur += step;
        s.boxes.push(textBox(el));
        if (s.cur > s.best) { s.best = s.cur; s.bestStart = s.start; s.bestBoxes = s.boxes; }
      } else s.cur = 0;
    });
  }
  return els.map((el, i) => {
    const text = el.textContent.replace(/\s+/g, ' ').trim();
    const words = text.split(' ').filter(Boolean).length;
    const s = stats[i];
    // judge placement on the settled layout: the middle of the longest readable span
    const b = s.bestBoxes.length ? s.bestBoxes[Math.floor(s.bestBoxes.length / 2)] : [0, 0, 0, 0];
    const safe = b[1] >= SAFE.top && b[3] <= SAFE.bottom && b[0] >= SAFE.left && b[2] <= SAFE.right;
    return { scene: el.closest('.scene').id.replace('s-', ''), text, words, secs: +s.best.toFixed(1), from: s.bestStart == null ? null : +s.bestStart.toFixed(1), wps: s.best ? +(words / s.best).toFixed(2) : null, box: b, safe };
  });
}, SAFE);
await browser.close();

console.log('# Readability & safe-zone audit\n');
console.log(`Generated by \`node tools/audit.mjs\`. "Readable" = element and its parents at >85% opacity on a visible scene; timing sampled every 0.1 s.`);
console.log(`Safe area checked: y ${SAFE.top}–${SAFE.bottom}px, x ${SAFE.left}–${SAFE.right}px on the 1080×1920 canvas (clear of top status/UI and bottom caption/CTA overlays).\n`);
console.log('| Scene | On-screen text | Words | Readable for | From | Words/sec | Box (x1,y1,x2,y2) | Safe |');
console.log('|---|---|---:|---:|---:|---:|---|:---:|');
let worst = 0, unsafe = 0;
for (const r of rows) {
  worst = Math.max(worst, r.wps || 0);
  if (!r.safe) unsafe++;
  console.log(`| ${r.scene} | ${r.text.replace(/\|/g, '/')} | ${r.words} | ${r.secs}s | ${r.from ?? '–'}s | ${r.wps ?? '–'} | ${r.box.join(',')} | ${r.safe ? '✓' : '⚠'} |`);
}
console.log(`\n**Elements:** ${rows.length} · **highest pace:** ${worst} words/sec · **outside safe area:** ${unsafe}`);
